shop/shop/apps/areas/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    # 提供qq登录扫描页面
    re_path(r'^areas/$',AreasView.as_view()),

]

shop/shop/apps/carts/urls.py
from django.urls import path,re_path,include
from .views import *
urlpatterns = [
    # 购物车管理
    re_path(r'^carts/$',CartsView.as_view(),name='info'),
    # 全选购物车
    re_path(r'^carts/selection/$',CartsSelectAllView.as_view()),
    # 展示购物车
    re_path(r'^carts/simple/$',CartsSimpleView.as_view()),

]

shop/shop/apps/goods/urls.py
from django.urls import re_path
from .views import *

urlpatterns = [
    # 商品列表页
    re_path(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$',ListView.as_view(),name='list'),
    # 热销排行
    re_path(r'^hot/(?P<category_id>\d+)/$',HotGoodsView.as_view()),
    # 商品详情
    re_path(r'^detail/(?P<sku_id>\d+)/$',DetailView.as_view(),name='detail'),
    # 商品统计
    re_path(r'^detail/visit/(?P<category_id>\d+)/$',DetailVisitView.as_view()),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 在include 的第二个参数中添加一个 namespace,避免不同应用中的路由使用了相同的名字发生冲突，使用命名空间区别开。
    # 这样的话 我们的name 就变为了 namespace:name
    # namespace 习惯上使用 子应用的名字

    # include((pattern_list, app_namespace), namespace=None)
        # 参数:
        # module -- URLconf 模块（或模块名称）
        # namespace (str) -- 包含的 URL 条目的实例命名空间。
        # pattern_list -- 可迭代的 path() 和／或 re_path() 实例。
        # app_namespace (str) -- 被包含的 URL 条目的应用命名空间

    # users
    re_path(r'^',include(('users.urls','users'),namespace='users')),
    # contents
    re_path(r'^', include(('contents.urls', 'contents'), namespace='contents')),
    # verifications
    re_path(r'^',include('verifications.urls')),
    # oauth
    re_path(r'^',include('oauth.urls')),
    # areas
    re_path(r'^',include('areas.urls')),
    # goods
    re_path(r'^',include(('goods.urls','goods'), namespace='goods')),
    # haystack
    re_path(r'^search/',include('haystack.urls')),
    # carts
    re_path(r'^',include(('carts.urls','goods'), namespace='carts')),
    # orders
    re_path(r'^',include(('orders.urls','orders'), namespace='orders')),
    # payment
    re_path(r'^',include(('payment.urls','payment'), namespace='payment')),
    # scheduler
    re_path(r'^',include('scheduler.urls')),
    # shop_admin
    re_path(r'^shop_admin/', include('shop_admin.urls')),

]

shop/shop/apps/areas/models.py
from django.db import models


# Create your models here.
class Area(models.Model):
    """省市区"""
    name = models.CharField(max_length=20, verbose_name='名称')
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, related_name='subs', null=True, blank=True, verbose_name='上级行政区划')

    class Meta:
        db_table = 'tb_areas'
        verbose_name = '省市区'
        verbose_name_plural = '省市区'

    def __str__(self):
        return self.name

shop/shop/apps/goods/models.py
from django.db import models
from fdfs_client.client import Fdfs_client
from shop.utils.models import BaseModel
# Create your models here.


'''
- models.CASCADE，删除关联数据，与之关联也删除
- models.DO_NOTHING，删除关联数据，引发错误IntegrityError
- models.PROTECT，删除关联数据，引发错误ProtectedError
- models.SET_NULL，删除关联数据，与之关联的值设置为null（前提FK字段需要设置为可空）
- models.SET_DEFAULT，删除关联数据，与之关联的值设置为默认值（前提FK字段需要设置默认值）
- models.SET，删除关联数据，
              a. 与之关联的值设置为指定值，设置：models.SET(值)
              b. 与之关联的值设置为可执行对象的返回值，设置：models.SET(可执行对象)
'''
class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    # 频道组名
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class GoodsCategory(BaseModel):
    """商品类别"""
    # 类别名称
    name = models.CharField(max_length=10, verbose_name='名称')
    # 父类别,自连接
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class GoodsChannel(BaseModel):
    # 所属频道组名
    group=models.ForeignKey(GoodsChannelGroup,on_delete=models.PROTECT, verbose_name='频道组名')
    # 顶级商品类别
    category = models.ForeignKey(GoodsCategory,on_delete=models.CASCADE,verbose_name='顶级商品类别')
    # 频道页面链接
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    # 组内顺序
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    # 品牌名称
    name = models.CharField(max_length=20, verbose_name='名称')
    # Logo图片链接
    logo = models.ImageField(verbose_name='Logo图片')
    # 品牌首字母
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class SPU(BaseModel):
    """商品SPU"""
    # 商品名称
    name = models.CharField(max_length=50, verbose_name='名称')
    # 品牌id
    brand=models.ForeignKey(Brand,on_delete=models.PROTECT, verbose_name='品牌')
    # 一级类别id
    category1 =models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    # 二级类别
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    # 三级类别
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    # 销量
    sales = models.IntegerField(default=0, verbose_name='销量')
    # 评价数
    comments = models.IntegerField(default=0, verbose_name='评价数')
    # 详细介绍
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    # 包装信息
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    # 售后服务
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    # 商品SKU名称
    name = models.CharField(max_length=50, verbose_name='名称')
    # 商品副标题
    caption = models.CharField(max_length=100, verbose_name='副标题')
    # spu商品id
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    # 从属类别id
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)

class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """SPU规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    # sku商品id
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    # spu规格名称id
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    # spu规格值的value
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)

class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    # 每一天每一个id生成多少访问量
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')
    category=models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

shop/shop/apps/shop_admin/models.py
from django.db import models

# Create your models here.

shop/shop/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
from django.core.cache import cache,caches # cache这个对象等价于 caches['default'] 。
import logging
from shop.utils.response_code import RETCODE
from .constants import province_city_REDIS_EXPIRES

from .models import Area
# Create your views here.
# 创建日志
logger=logging.getLogger('areas')

class AreasView(View):
    """省市区三级联动"""

    def get(self,request):
        # 根据get请求参数，判断当前是查询省份数据还是市区，
        cache1=caches['ProvinceCity']
        area_id=request.GET.get('area_id')
        if not area_id:
            # 获取并判断是否有省级缓存数据
            province_list=cache1.get('province_list')
            if not province_list:
                # 查询省级数据
                try:
                    province_model_list=Area.objects.filter(parent__isnull=True) # 返回集合
                    province_list=[]
                    for province_model in province_model_list:
                        province_list.append({'id': province_model.id, 'name': province_model.name})
                    # 存储省份列表缓存数据:默认存储到别名为"default"
                    cache1.set('province_list', province_list, province_city_REDIS_EXPIRES)
                except Exception as e:
                    logger.error(e)
                    return JsonResponse({'code':RETCODE.DBERR,"errmsg":'查询省份数据错误'})
            context = {'code': RETCODE.OK, "errmsg": 'OK', "province_list": province_list}
            return JsonResponse(context)
        else:
            # 查询市和区的数据
            sub_data=cache1.get('sub_area_'+area_id)
            if not sub_data:# redis没有，查询mysql
                try:
                    parent_model = Area.objects.get(id=area_id)  # 查询市或区的父级模型
                   #  sub_model_list=parent_model.area_set.all(),由于模型的定义数据参数related_name='subs'
                    sub_model_list = parent_model.subs.all()
                    # 序列化市或区数据
                    sub_list = []
                    for sub_model in sub_model_list:
                        sub_list.append({'id': sub_model.id, 'name': sub_model.name})
                        """
                        {
                          "code":"0",
                          "errmsg":"OK",
                          "sub_data":{
                              "id":130000,
                              "name":"河北省",
                              "subs":[
                                  {
                                      "id":130100,
                                      "name":"石家庄市"
                                  },
                                  ......
                              ]
                        """
                    # 储存市或区缓存数据
                    sub_data={
                                  "id":parent_model.id,
                                   'name':parent_model.name,
                                   'subs':sub_list
                              }
                    # 存储市或县列表缓存数据:默认存储到别名为"default"
                    cache1.set('sub_area_' + area_id, sub_data, 3600)
                except Exception as e:
                    logger.error(e)
                    return JsonResponse({'code':RETCODE.DBERR,"errmsg":'查询省份数据错误'})
            # 响应城市或区JSON数据
            context = {'code': RETCODE.OK, "errmsg": 'OK', "sub_data": sub_data}
            return JsonResponse(context)

shop/shop/apps/contents/views.py
from django.shortcuts import render,reverse
from django.views import View
from collections import OrderedDict



from contents.utils import get_categories
from goods.models import *
from contents.models import *



# Create your views here.
class IndexView(View):
    '''
    首页广告
    '''
    def get(self,request):
        '''提供首页广告页面'''


        """1、查询并展示商品分类"""
        channel_group_list=get_categories()

        """2、查询首页广告数据"""
        # 第一步：查询所有广告类别
        contents=OrderedDict()
        contentCategory_list=ContentCategory.objects.all()
        for contentCategory in contentCategory_list:
            # 查询未下架的广告并排序
            content_list=contentCategory.content_set.filter(status=True).order_by('sequence')
            contents[contentCategory.key]=content_list
            # 第二步：使用广告类别查询出该类别对应的广告内容

        context={'categories':channel_group_list,'contents':contents}
        # print(reverse('contents:index'))
        return render(request,'index.html',context)

shop/shop/apps/shop_admin/views/PageNum.py
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response


class PageNum(PageNumberPagination):

    #默认值与 PAGE_SIZE 设置键相同。 如果设置了，则settings.py重写 PAGE_SIZE 。
    # page_size显示<max_page_size
    page_size = 5
    # 指定查询参数的名称，该参数允许客户端根据每个请求设置页面大小。
    # 默认为“无”，表示客户端可能无法控制请求的页面大小。
    page_size_query_param = 'pagesize'
    # 指示所请求的页面大小的最大允许值。只有当 page_size_query_param 也被设置时，此属性才有效。
    max_page_size =10

    # 重写分页返回方法，按照指定的字段进行分页数据返回
    def get_paginated_response(self, data):
        return Response({
            'count': self.page.paginator.count,  # 总数量
            'lists': data,  # 用户数据
            'page' : self.page.number, # 当前页数
            'pages' : self.page.paginator.num_pages, # 总页数
            'pagesize':self.page_size  # 后端指定的页容量
        })

shop/shop/apps/shop_admin/views/SpecsViewSet.py
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAdminUser

from goods.models import SPUSpecification,SPU
from shop_admin.serializers.specs_serializer import SpecsSerializer,SPUSerializer
from shop_admin.views.PageNum import PageNum

class SpecsView(ModelViewSet):
    # 权限指定
    permission_classes=[IsAdminUser]

    """
    使用视图集ViewSet，可以将一系列逻辑相关的动作放到一个类中：
    list() 提供一组数据
    retrieve() 提供单个数据
    create() 创建数据
    update() 保存数据
    destory() 删除数据
    ViewSet视图集类不再实现get()、post()等方法，而是实现动作 action 如 list() 、create() 等。

    3）ModelViewSet
    继承自GenericAPIVIew，同时包括了ListModelMixin、RetrieveModelMixin、
        CreateModelMixin、UpdateModelMixin、DestoryModelMixin。
    """

    """商品的规格表所有操作：增删改查"""
    # 1、要指定当前类视图使用的查询数据
    queryset = SPUSpecification.objects.all()
    # 2、要指定当前视图使用的序列化器
    serializer_class =SpecsSerializer
    # 3、指定分页器，会调用ModelMixin的list方法
    pagination_class =PageNum

    # 由于ModelViewSet继承ModelMixin的list、update、retrieve、destory、create方法,不需要写

    def simple(self,request):
        """
        获取SPU规格所关联的信息
        :param request:
        :return:
        """
        spus=SPU.objects.all()
        serializer=SPUSerializer(spus,many=True)
        return Response(serializer.data)

shop/shop/apps/shop_admin/views/UsersView.py
from rest_framework.generics import ListCreateAPIView
from rest_framework.permissions import IsAdminUser

from shop_admin.views.PageNum import PageNum
from shop_admin.serializers import User_serializer
from users.models import User



class UserView(ListCreateAPIView):
    """用户管理"""
    # 权限指定
    permission_classes = [IsAdminUser]

    # 1、要指定当前类视图使用的查询数据
    # 重写get_queryset方法，根据前端是否传递keyword值返回不同查询结果
    def get_queryset(self):
        """查询数据"""
        # 获取前端传递的keyword值
        keyword = self.request.query_params.get('keyword')
        if keyword is None or keyword is '':
            return User.objects.all()
        else:
            return User.objects.filter(username__icontains=keyword)

    # 2、要指定当前视图使用的序列化器
    # serializer_class =User_serializer.UserSerializer
    def get_serializer_class(self):
        # 请求方式是GET，则是获取用户数据返回UserSerializer
        if self.request.method == 'GET':
            return User_serializer.UserSerializer
        else:
            # POST请求，完成保存用户，返回UserAddSerializer
            return User_serializer.UserAddSerializer

    # 3、指定分页器，会调用ModelMixin的list方法
    pagination_class = PageNum

shop/shop/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-登录</title>
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
	<script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="{{ url('contents:index') }}" class="login_logo"><img src="{{ static('images/logo02.png') }}"></a>
	</div>
	<div class="login_form_bg" id="app">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">商品美 · 种类多 · 欢迎光临</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<a href="javascript:;" class="cur">账户登录</a>
				</div>
				<div class="form_con">
					<div class="form_input cur">
						<form method="post" class="login-form" @submit="on_submit" v-cloak>
                            {{ csrf_input }}
							<input type="text" v-model="username" @blur="check_username" name="username" class="name_input" placeholder="请输入用户名或手机号">
							<div v-show="error_username" class="user_error">请输入正确的用户名或手机号</div>
							<input type="password" v-model="password" @blur="check_password" name="password" class="pass_input" placeholder="请输入密码">
							<div v-show="error_password" class="pwd_error">密码最少8位，最长20位</div>
							{% if account_errmsg  %}
                            <div class="pwd_error">{{ account_errmsg }}</div>
                            {% endif %}
                            <div class="more_input clearfix">
								<input type="checkbox" v-model="remembered" name="remembered">
								<label>记住登录</label>
							</div>
							<input type="submit" value="登 录" class="input_submit">
						</form>
					</div>
				</div>
				<div class="third_party">
					<a @click="qq_login" class="qq_login">QQ</a>
					<a href="#" class="weixin_login">微信</a>
					<a href="{{ url('users:register') }}" class="register_btn">立即注册</a>
				</div>
			</div>
		</div>
	</div>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script type="text/javascript" src="{{ static('js/common.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/login.js') }}"></script>
</body>
</html>

shop/shop/templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-我的订单</title>
	<link rel="stylesheet" type="text/css" href="{{ static('css/jquery.pagination.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
    <script type="text/javascript" src="{{ static('js/jquery-1.12.4.min.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
	<div id="app">
	<div class="header_con">
		<div class="header" v-cloak>
			<div class="welcome fl">欢迎来到美多商城!</div>
			<div class="fr">
                <div v-if="username" class="login_btn fl">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="{{ url('users:logout') }}">退出</a>
                </div>
                <div v-else class="login_btn fl">
                    <a href="{{ url('users:login') }}">登录</a>
                    <span>|</span>
                    <a href="{{ url('users:register') }}">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{{ url('users:info') }}">用户中心</a>
					<span>|</span>
					<a href="{{ url('carts:info') }}">我的购物车</a>
					<span>|</span>
					<a href="{{ url('orders:settlement') }}">我的订单</a>
                    <span>|</span>
					<a href="{{ url('orders:info', args=(1, )) }}">全部订单</a>
				</div>
			</div>
		</div>		
	</div>
	<div class="search_bar clearfix">
		<a href="{{ url('contents:index') }}" class="logo fl"><img src="{{ static('images/logo.png') }}"></a>
		<div class="search_wrap fl">
			<form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
			<ul class="search_suggest fl">
				<li><a href="#">索尼微单</a></li>
				<li><a href="#">优惠15元</a></li>
				<li><a href="#">美妆个护</a></li>
				<li><a href="#">买2免1</a></li>
			</ul>
		</div>
	</div>
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{{ url('users:info') }}">· 个人信息</a></li>
				<li><a href="{{ url('users:address') }}">· 收货地址</a></li>
                <li><a href="{{ url('orders:info', args=(1, )) }}" class="active">· 全部订单</a></li>
				<li><a href="{{ url('users:pass') }}">· 修改密码</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page_orders %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time.strftime('%Y-%m-%d %H:%M:%S') }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
            </ul>
            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            {% for sku in order.sku_list %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                <li class="col02"><span>{{ sku.name }}</span><em>{{ sku.price }}元</em></li>
                                <li class="col03">{{ sku.count }}</li>
                                <li class="col04">{{ sku.amount }}元</li>
                            </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br>含运费：{{ order.freight }}元</td>
                        <td width="15%">{{ order.pay_method }}</td>
                        <td width="15%">
                            <a @click="oper_btn_click('{{ order.order_id }}', {{ order.status }})" class="oper_btn">{{ order.status_name }}</a>
                        </td>
                    </tr>
                </tbody>
            </table>
            {% endfor %}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
        </div>
	</div>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	</div>
    <script type="text/javascript" src="{{ static('js/common.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/user_center_order.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/jquery.pagination.min.js') }}"></script>
	<script type="text/javascript">
        $(function () {
            $('#pagination').pagination({
                currentPage: {{ page_num }},
                totalPage: {{ total_page }},
                callback:function (current) {
                     location.href = '/orders/info/' + current + '/';
                }
            })
        });
    </script>
</body>
</html>